service: aws-nodejs 

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  iamRoleStatements: 
    - "Sid": "Stmt1468366974000"
      "Effect": "Allow"
      "Action": "s3:*"
      "Resource": ["arn:aws:s3:::topic-storage/*"]
functions:
  prepareTopics:
    handler: handler.prepareTopics
    events:
      - schedule: rate(2 hours)
